//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanasVehicleTrackDbClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMaster
    {
        public int Userid { get; set; }
        public string Username { get; set; }
        public string UserPassword { get; set; }
        public Nullable<bool> Activestatus { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createuser { get; set; }
        public string Companycode { get; set; }
    }
}
